# Generated by Django 5.2 on 2025-06-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tipe',
            field=models.CharField(default='Event', max_length=20),
        ),
    ]
