# Generated by Django 5.2 on 2025-06-12 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0002_profile_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_organization',
            field=models.BooleanField(default=False),
        ),
    ]
