# Generated by Django 5.2 on 2025-05-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_remove_article_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(default='Artikel', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='tipe',
            field=models.CharField(default='Artikel', max_length=20),
        ),
    ]
