# Generated by Django 5.2 on 2025-06-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_comment_user_reply_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='tipe',
            field=models.CharField(default='Pengumuman', max_length=20),
        ),
    ]
